Update Mission Statement
dbt-labs/corp pull request #62
Opened 2022-06-07 19:58 UTC by sierrafontaine

Open to suggestion here, maybe "data professionals" - but got some feedback that "data analyst" doesn't capture all of the people that use dbt, so it may be time for a refresh!

2022-06-08 12:20 UTC, jthandy requested changes
I don't think "data humans" is very well-defined. What we must avoid with our mission and values is for them to be "squishy"--they have to be extremely clear. In order to say "yes this is the mission" or "no this is not the mission" that clarity is critical. 

It then becomes critical to know whom we are empowering. Who is a "data human"? This is unanswerable. We could define what we mean by this, but going into a lengthy definition defeats one of the purposes of the mission: to succinctly, memorably communicate about purpose.

So IMO "data human" is a no go.

I'm open to "data professionals". I think it is specific, clear, and memorable. I also think that it is _true_. I agree with the core assertion of this PR that "analysts" is not a sufficiently-wide grouping to target our mission at any more. This might have been the correct answer ~3 years ago when this version was merged, but we've evolved a lot since then.

2022-07-11 14:15 UTC, lostmygithubaccount commented
+1 for data professionals. in ML product land we used "ML professionals" for the same reasoning -- there are a lot of titles (data scientist, ML engineer, ML/AI researcher, data wranglers, ML app devs, MLOps engineer, ...) and it's much easier to lump them all together into a neutral term when talking generally about users

2022-07-13 12:03 UTC, jthandy commented
@sierrafontaine please change this to "data practitioner" and then we can merge. thanks!

2022-07-13 14:41 UTC, brian-gillet commented on mission.md
> +To empower data professionals to create and disseminate organizational knowledge.
Misspelled practitioners @dataders - can you please update the spelling in the commit?

2022-07-13 15:05 UTC, dataders commented on mission.md
> +To empower data professionals to create and disseminate organizational knowledge.
whoops! I thought it looked funny!
```suggestion
To empower data practitioners to create and disseminate organizational knowledge.
```

2022-07-13 22:35 UTC, ericalouie approved these changes
LGTM 🥳

2022-07-13 22:36 UTC, merged