remove metrics style guide
dbt-labs/corp pull request #95
Opened 2023-07-25 03:21 UTC by Jstein77

This PR removes the outdated metrics style guide.

2023-07-25 11:59 UTC, jthandy commented
@Jstein77 assuming we're replacing this with something?

2023-07-25 15:11 UTC, Jstein77 commented
@jthandy Yes! Winnne and I are working on an updated set up best practices and style guide. In terms of sequencing, I think it would be best to remove this page so we don't have materials referencing the old metrics spec. We should have something to replace it with by the end of the week.

2023-08-07 23:19 UTC, closed without merging

2023-08-07 23:25 UTC, dbeatty10 requested changes

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +## Organizing Semantic Model
Pluralize?
```suggestion
## Organizing Semantic Models
```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +- Semantic models are created in the same yml file where you define configs, tests and metrics for your models. There should be one yml file per model.
Use the same capitalization of YAML that appears throughout the rest of the file:

```suggestion
- Semantic models are created in the same YAML file where you define configs, tests and metrics for your models. There should be one YAML file per model.

```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +						├── products.yml #semantic models defined here
Similar to the [Python style guide for comments in PEP-8](https://peps.python.org/pep-0008/#inline-comments), inline comments in YAML should be separated by at least two spaces from the statement. They should start with a # and a single space.

```suggestion
						├── orders.yml  # semantic models defined here
    ├── staging
			  ├── product
				    ├── products.sql
						├── products.yml  # semantic models defined here

```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +- Metrics are created in the same yml file where you define configs, tests and semantic models for your models.
```suggestion
- Metrics are created in the same YAML file where you define configs, tests and semantic models for your models.

```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +						├── products.yml  #metrics defined here
```suggestion
						├── orders.yml  # metrics defined here
    ├── staging
			  ├── product
				    ├── products.sql
						├── products.yml  # metrics defined here

```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +  #The name of the semantic model.
```suggestion
  # The name of the semantic model.
```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +    #The name of the dbt model and schema
```suggestion
    # The name of the dbt model and schema
```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +    #Entities. These usually corespond to keys in the table.
```suggestion
    # Entities. These usually corespond to keys in the table.
```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +  #Dimensions. Either categorical or time. These add additonal context to metrics. The typical querying pattern is Metric by Dimension.
```suggestion
  # Dimensions. Either categorical or time. These add additonal context to metrics. The typical querying pattern is Metric by Dimension.  
```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +  #Dimensions. Either categorical or time. These add additonal context to metrics. The typical querying pattern is Metric by Dimension.
Fix misspelling and comment spacing:
```suggestion
  # Dimensions. Either categorical or time. These add additional context to metrics. The typical querying pattern is Metric by Dimension.  
```

2023-08-07 23:25 UTC, dbeatty10 commented on dbt_style_guide.md
> +	          alias: cost
Replacing tabs with spaces:
```suggestion
        - name: order_gross_profit
            description: Gross profit from each order.
            type: derived
            label: Order Gross Profit
            type_params:
              expr: revenue - cost
              metrics:
                - name: revenue
                - name: order_cost
                  alias: cost
```